<!DOCTYPE process [
        <!ELEMENT process (subsheet|stage)*>
        <!ATTLIST process
                name CDATA #REQUIRED>
        <!ELEMENT subsheet (name)*>
        <!ATTLIST subsheet
                subsheetid CDATA #REQUIRED>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT stage (onsuccess|datatype|initialvalue|exposure|alwaysinit|subsheetid|private|resource|exception|loginhibit|decision|ontrue|onfalse|processid|calculation|steps|initialvalueenc|collectioninfo)*>
        <!ATTLIST stage
                name CDATA #REQUIRED
                stageid CDATA #REQUIRED
                type CDATA #REQUIRED>
        <!ELEMENT onsuccess (#PCDATA)>
        <!ELEMENT datatype (#PCDATA)>
        <!ELEMENT initialvalue (singlerow|row)*>
        <!ATTLIST initialvalue
                xml:space CDATA #IMPLIED>
        <!ELEMENT exposure (#PCDATA)>
        <!ELEMENT alwaysinit (#PCDATA)>
        <!ELEMENT subsheetid (#PCDATA)>
        <!ELEMENT private (#PCDATA)>
        <!ELEMENT resource (#PCDATA)>
        <!ATTLIST resource
                action CDATA #REQUIRED
                object CDATA #REQUIRED>
        <!ELEMENT exception (#PCDATA)>
        <!ATTLIST exception
                detail CDATA #REQUIRED
                type CDATA #REQUIRED
                usecurrent CDATA #IMPLIED>
        <!ELEMENT loginhibit (#PCDATA)>
        <!ATTLIST loginhibit
                onsuccess CDATA #REQUIRED>
        <!ELEMENT decision (#PCDATA)>
        <!ATTLIST decision
                expression CDATA #REQUIRED>
        <!ELEMENT ontrue (#PCDATA)>
        <!ELEMENT onfalse (#PCDATA)>
        <!ELEMENT processid (#PCDATA)>
        <!ELEMENT calculation (#PCDATA)>
        <!ATTLIST calculation
                expression CDATA #REQUIRED
                stage CDATA #REQUIRED>
        <!ELEMENT steps (calculation)*>
        <!ELEMENT initialvalueenc (#PCDATA)>
        <!ELEMENT collectioninfo (singlerow|field)*>
        <!ELEMENT singlerow (#PCDATA)>
        <!ELEMENT field (#PCDATA)>
        <!ATTLIST field
                name CDATA #REQUIRED
                type CDATA #REQUIRED
                value CDATA #IMPLIED>
        <!ELEMENT row (field)*>
        ]>
<process name="POC">
  <subsheet subsheetid="959ff625-d504-46a0-8f6f-2930188215fe">
    <name>Start Up</name>
  </subsheet>
  <subsheet subsheetid="8d4786ca-281a-4044-8e18-eb97d785b992" >
    <name>Close Down</name>
  </subsheet>
  <subsheet subsheetid="fc4e6ade-7a8d-4587-bfe3-21dbe933d8eb" >
    <name>Populate Queue</name>
  </subsheet>
  <subsheet subsheetid="614059a1-8f73-40c0-9dab-a3e78c79ecad" >
    <name>Recup Info PJ</name>
  </subsheet>
  <subsheet subsheetid="61a0ac13-8edb-407b-9f5c-21990581f384" >
    <name>01 - Recherche Fournisseur</name>
  </subsheet>
  <subsheet subsheetid="b9d01bbd-d50f-408d-a57d-f5def6ddbaf6" >
    <name>02 - Finalisation</name>
  </subsheet>
  <subsheet subsheetid="0419341b-8a5d-45b3-9ca3-71b8d47ffff0" >
    <name>Notify Exception + Restart</name>
  </subsheet>
  <subsheet subsheetid="4bf72baa-85cd-49b1-aee7-2f7173f35a18" >
    <name>Termination</name>
  </subsheet>
  <subsheet subsheetid="0fd80767-2fc1-41e9-ae80-73ac1738dda1" >
    <name>Mark Item As Completed</name>
  </subsheet>
  <subsheet subsheetid="bb122fc4-3e3e-4e96-acb7-62104bb07f35" >
    <name>Mark Item As Exception</name>
  </subsheet>
  <stage stageid="9297f103-7b38-46e4-a87a-90bc40fdb0c5" name="Start" type="Start">
    <onsuccess>50c75180-1cb4-41f0-983f-5c13b2edb165</onsuccess>
  </stage>
  <stage stageid="81952add-924e-40a6-a011-1afe5fb3655a" name="Stage1" type="ProcessInfo">
  </stage>
  <stage stageid="ebdda353-6393-46f6-b5f4-6ab463dcdb7c" name="FDO - Chemin Dossier Travail" type="Data">
    <datatype>text</datatype>
    <initialvalue />
    <exposure>Environment</exposure>
    <alwaysinit />
  </stage>
  <stage stageid="06f9485c-ef1c-47cf-b873-81a1b0da3aef" name="Recup Info PJ" type="SubSheetInfo">
    <subsheetid>614059a1-8f73-40c0-9dab-a3e78c79ecad</subsheetid>
  </stage>
  <stage stageid="dbf79c9e-149e-48a3-b2d2-4b5b00956d34" name="Start" type="Start">
    <subsheetid>614059a1-8f73-40c0-9dab-a3e78c79ecad</subsheetid>
    <onsuccess>f38e5a9f-be30-45bc-afba-eb140014c929</onsuccess>
  </stage>
  <stage stageid="5065f292-a339-424a-a8cc-390fdbae59c2" name="End" type="End">
    <subsheetid>614059a1-8f73-40c0-9dab-a3e78c79ecad</subsheetid>
  </stage>
  <stage stageid="3f2f1a16-c35f-454f-8b83-8edf09fb5d30" name="Nom PJ" type="Data">
    <subsheetid>614059a1-8f73-40c0-9dab-a3e78c79ecad</subsheetid>
    <datatype>text</datatype>
    <initialvalue />
    <private />
    <alwaysinit />
  </stage>
  <stage stageid="f38e5a9f-be30-45bc-afba-eb140014c929" name="Create Instance" type="Action">
    <subsheetid>614059a1-8f73-40c0-9dab-a3e78c79ecad</subsheetid>
    <onsuccess>c6387b8e-7047-4704-b17f-b09d01c49798</onsuccess>
    <resource object="MS Excel VBO" action="Create Instance" />
  </stage>
  <stage stageid="bb9de41b-f1ad-40ad-b722-3ecd5b348057" name="handle" type="Data">
    <subsheetid>614059a1-8f73-40c0-9dab-a3e78c79ecad</subsheetid>
    <datatype>number</datatype>
    <initialvalue />
    <private />
    <alwaysinit />
  </stage>
  <stage stageid="c6387b8e-7047-4704-b17f-b09d01c49798" name="Open Workbook" type="Action">
    <subsheetid>614059a1-8f73-40c0-9dab-a3e78c79ecad</subsheetid>
    <onsuccess>54553578-5e67-4803-8f13-f19c33041823</onsuccess>
    <resource object="MS Excel VBO" action="Open Workbook" />
  </stage>
  <stage stageid="6c373df1-ba4d-4846-afba-d67060cc79eb" name="Workbook Name" type="Data">
    <subsheetid>614059a1-8f73-40c0-9dab-a3e78c79ecad</subsheetid>
    <datatype>text</datatype>
    <initialvalue />
    <private />
    <alwaysinit />
  </stage>
  <stage stageid="54553578-5e67-4803-8f13-f19c33041823" name="Show" type="Action">
    <subsheetid>614059a1-8f73-40c0-9dab-a3e78c79ecad</subsheetid>
    <onsuccess>706c7e65-9803-4703-8066-079ca1ebfbdb</onsuccess>
    <resource object="MS Excel VBO" action="Show" />
  </stage>
  <stage stageid="83990bdd-2a6b-438c-8bda-e87387704851" name="Fermer Excel" type="Action">
    <subsheetid>614059a1-8f73-40c0-9dab-a3e78c79ecad</subsheetid>
    <onsuccess>5065f292-a339-424a-a8cc-390fdbae59c2</onsuccess>
    <resource object="MS Excel VBO" action="Exit" />
  </stage>
  <stage stageid="eb2a95a7-2437-4b60-b471-b47fdeb24aa2" name="Get worksheet as collection" type="Action">
    <subsheetid>614059a1-8f73-40c0-9dab-a3e78c79ecad</subsheetid>
    <onsuccess>83990bdd-2a6b-438c-8bda-e87387704851</onsuccess>
    <resource object="MS Excel VBO" action="Get Worksheet As Collection" />
  </stage>
  <stage stageid="5a160227-eebf-4e17-8cba-03896220b578" name="Data" type="Collection">
    <subsheetid>614059a1-8f73-40c0-9dab-a3e78c79ecad</subsheetid>
    <datatype>collection</datatype>
    <private />
    <alwaysinit />
  </stage>
  <stage stageid="706c7e65-9803-4703-8066-079ca1ebfbdb" name="Get first worksheet name" type="Action">
    <subsheetid>614059a1-8f73-40c0-9dab-a3e78c79ecad</subsheetid>
    <onsuccess>eb2a95a7-2437-4b60-b471-b47fdeb24aa2</onsuccess>
    <resource object="MS Excel VBO" action="Get Worksheet Name" />
  </stage>
  <stage stageid="9d49e530-a958-4fea-99cf-f0d59b4226b4" name="Worksheet" type="Data">
    <subsheetid>614059a1-8f73-40c0-9dab-a3e78c79ecad</subsheetid>
    <datatype>text</datatype>
    <initialvalue />
    <private />
    <alwaysinit />
  </stage>
  <stage stageid="3ad5be7b-3e79-428c-b4ae-56f70dbe3e09" name="Block1" type="Block">
    <subsheetid>614059a1-8f73-40c0-9dab-a3e78c79ecad</subsheetid>
  </stage>
  <stage stageid="316950fa-761f-4aef-9173-7483408c2ee7" name="Recover1" type="Recover">
    <subsheetid>614059a1-8f73-40c0-9dab-a3e78c79ecad</subsheetid>
    <onsuccess>d5a33a4b-3a6e-4230-adc1-42c813732c4c</onsuccess>
  </stage>
  <stage stageid="d5a33a4b-3a6e-4230-adc1-42c813732c4c" name="Fermer Excel" type="Action">
    <subsheetid>614059a1-8f73-40c0-9dab-a3e78c79ecad</subsheetid>
    <onsuccess>082bbd90-784e-4b0e-bd08-d9a7f6e5339d</onsuccess>
    <resource object="MS Excel VBO" action="Exit" />
  </stage>
  <stage stageid="082bbd90-784e-4b0e-bd08-d9a7f6e5339d" name="Exception1" type="Exception">
    <subsheetid>614059a1-8f73-40c0-9dab-a3e78c79ecad</subsheetid>
    <exception type="" detail="" usecurrent="yes" />
  </stage>
  <stage stageid="05e38e92-96cf-48aa-a844-199056efebf1" name="01 - Recherche Fournisseur" type="SubSheetInfo">
    <subsheetid>61a0ac13-8edb-407b-9f5c-21990581f384</subsheetid>
  </stage>
  <stage stageid="d697e46f-aa11-40d6-8edb-1d3e8a297a57" name="Start" type="Start">
    <subsheetid>61a0ac13-8edb-407b-9f5c-21990581f384</subsheetid>
    <onsuccess>d5fd6f2b-7320-437f-ae16-a917e34c5b19</onsuccess>
  </stage>
  <stage stageid="b4d86fb7-02d1-403c-8cc7-5a7f3c9cf161" name="End" type="End">
    <subsheetid>61a0ac13-8edb-407b-9f5c-21990581f384</subsheetid>
  </stage>
  <stage stageid="16876a86-31a0-4ba0-9278-c529eb4a859b" name="ENVIRONNEMENT VARIABLES" type="Block">
    <loginhibit onsuccess="true" />
  </stage>
  <stage stageid="779ffd9a-78bf-4517-83c5-286cc8064a11" name="OUT" type="Block">
    <loginhibit onsuccess="true" />
  </stage>
  <stage stageid="badb0ad3-f38c-4bd7-b015-72adfc255cfb" name="IN" type="Block">
    <loginhibit onsuccess="true" />
  </stage>
  <stage stageid="139901e4-d817-4e07-aeec-05985c96c98d" name="CONSTANTES" type="Block">
    <loginhibit onsuccess="true" />
  </stage>
  <stage stageid="4d106996-be35-40a4-9bc9-6d132f1ee70c" name="Note3" type="Note">
    <loginhibit onsuccess="true" />
  </stage>
  <stage stageid="e20035e5-644c-4859-91b5-45f02e75cbbf" name="Got Item?" type="Decision">
    <loginhibit onsuccess="true" />
    <decision expression="[Item.Item ID]&lt;&gt;&quot;&quot;" />
    <ontrue>f9264c47-2edb-426b-91ff-0d3264ce364c</ontrue>
    <onfalse>1a576eec-bb70-4543-8feb-c2a195f25c81</onfalse>
  </stage>
  <stage stageid="7ce59389-58f1-4f79-a9b3-9aef63fb39ba" name="Stop?" type="Decision">
    <loginhibit onsuccess="true" />
    <decision expression="IsStopRequested()" />
    <ontrue>72a5311a-0ea9-4c46-8feb-fbb3e4621eb2</ontrue>
    <onfalse>5469f1de-55f1-4d23-990c-f0a221ab96f6</onfalse>
  </stage>
  <stage stageid="434d9671-fb76-4fa2-ad29-5d9505d4846d" name="Get Next Item" type="Action">
    <loginhibit onsuccess="true" />
    <onsuccess>e20035e5-644c-4859-91b5-45f02e75cbbf</onsuccess>
    <resource object="Blueprism.Automate.clsWorkQueuesActions" action="Get Next Item" />
  </stage>
  <stage stageid="1a576eec-bb70-4543-8feb-c2a195f25c81" name="Populate Queue" type="SubSheet">
    <loginhibit onsuccess="true" />
    <onsuccess>f12a8a70-f501-4e67-ad90-37c3472afd54</onsuccess>
    <processid>fc4e6ade-7a8d-4587-bfe3-21dbe933d8eb</processid>
  </stage>
  <stage stageid="f12a8a70-f501-4e67-ad90-37c3472afd54" name="Loaded Queue ?" type="Decision">
    <loginhibit onsuccess="true" />
    <decision expression="[Queue Loaded]" />
    <ontrue>5469f1de-55f1-4d23-990c-f0a221ab96f6</ontrue>
    <onfalse>72a5311a-0ea9-4c46-8feb-fbb3e4621eb2</onfalse>
  </stage>
  <stage stageid="5469f1de-55f1-4d23-990c-f0a221ab96f6" name="Get Next Item" type="Action">
    <loginhibit onsuccess="true" />
    <onsuccess>e20035e5-644c-4859-91b5-45f02e75cbbf</onsuccess>
    <resource object="Blueprism.Automate.clsWorkQueuesActions" action="Get Next Item" />
  </stage>
  <stage stageid="72a5311a-0ea9-4c46-8feb-fbb3e4621eb2" name="Close Down" type="SubSheet">
    <loginhibit onsuccess="true" />
    <onsuccess>f8be8eae-2cb8-4d1a-9325-473869b93525</onsuccess>
    <processid>8d4786ca-281a-4044-8e18-eb97d785b992</processid>
  </stage>
  <stage stageid="9189828a-6681-4eaa-89a9-21f427d2435b" name="CONST - Queue Name" type="Data">
    <loginhibit onsuccess="true" />
    <datatype>text</datatype>
    <initialvalue xml:space="preserve">BNP-PF_AIA_QUEUE_ADVERSE_INFORMATION_ANALYSIS</initialvalue>
    <private />
    <alwaysinit />
  </stage>
  <stage stageid="50c75180-1cb4-41f0-983f-5c13b2edb165" name="Start Up" type="SubSheet">
    <loginhibit onsuccess="true" />
    <onsuccess>434d9671-fb76-4fa2-ad29-5d9505d4846d</onsuccess>
    <processid>959ff625-d504-46a0-8f6f-2930188215fe</processid>
  </stage>
  <stage stageid="f8be8eae-2cb8-4d1a-9325-473869b93525" name="End" type="End">
  </stage>
  <stage stageid="76cf5967-d97e-4102-9a0b-4908e9f9478b" name="Populate Queue" type="SubSheetInfo">
    <subsheetid>fc4e6ade-7a8d-4587-bfe3-21dbe933d8eb</subsheetid>
  </stage>
  <stage stageid="49efc659-fe97-41a1-b6fa-35325a92812a" name="Start" type="Start">
    <subsheetid>fc4e6ade-7a8d-4587-bfe3-21dbe933d8eb</subsheetid>
    <onsuccess>0b9ed65a-df3d-4155-9d96-be23699ab728</onsuccess>
  </stage>
  <stage stageid="493b41b3-bd7a-427b-b3bf-bfe000f535df" name="Start Up" type="SubSheetInfo">
    <subsheetid>959ff625-d504-46a0-8f6f-2930188215fe</subsheetid>
  </stage>
  <stage stageid="75425053-6d53-447e-8121-e68836dfa200" name="Start" type="Start">
    <subsheetid>959ff625-d504-46a0-8f6f-2930188215fe</subsheetid>
    <onsuccess>02a104e4-4967-419b-9cfe-ced64c2e18ff</onsuccess>
  </stage>
  <stage stageid="7da78c16-175d-419d-b9db-868c8793a070" name="End" type="End">
    <subsheetid>959ff625-d504-46a0-8f6f-2930188215fe</subsheetid>
  </stage>
  <stage stageid="b252cc2f-75fd-444d-a754-7587835cd370" name="Close Down" type="SubSheetInfo">
    <subsheetid>8d4786ca-281a-4044-8e18-eb97d785b992</subsheetid>
  </stage>
  <stage stageid="d4fb74c3-cb2c-4c8a-8d90-349e402f5aef" name="Start" type="Start">
    <subsheetid>8d4786ca-281a-4044-8e18-eb97d785b992</subsheetid>
    <onsuccess>506ee3d5-1109-4659-b89c-7af9bd2ac316</onsuccess>
  </stage>
  <stage stageid="82af25d9-f032-496b-82a0-209c738dc384" name="End" type="End">
    <subsheetid>8d4786ca-281a-4044-8e18-eb97d785b992</subsheetid>
  </stage>
  <stage stageid="bdf8a487-cdd7-436b-bded-da96bda77707" name="INTERNAL" type="Block">
    <loginhibit onsuccess="true" />
  </stage>
  <stage stageid="090f9673-8c2d-444f-a3ff-3b1d0c7d2f83" name="INTERNAL" type="Block">
    <subsheetid>959ff625-d504-46a0-8f6f-2930188215fe</subsheetid>
    <loginhibit onsuccess="true" />
  </stage>
  <stage stageid="84cdd598-ad18-4db5-8bb9-4f528c90c7fd" name="OUT" type="Block">
    <subsheetid>959ff625-d504-46a0-8f6f-2930188215fe</subsheetid>
    <loginhibit onsuccess="true" />
  </stage>
  <stage stageid="eb759a53-9415-4365-a381-b07a1af09203" name="IN" type="Block">
    <subsheetid>959ff625-d504-46a0-8f6f-2930188215fe</subsheetid>
    <loginhibit onsuccess="true" />
  </stage>
  <stage stageid="91896f4c-7766-4572-8bb8-8d3643710008" name="INTERNAL" type="Block">
    <subsheetid>8d4786ca-281a-4044-8e18-eb97d785b992</subsheetid>
    <loginhibit onsuccess="true" />
  </stage>
  <stage stageid="3becd9ed-3f81-403c-a905-686bee6cb9ca" name="OUT" type="Block">
    <subsheetid>8d4786ca-281a-4044-8e18-eb97d785b992</subsheetid>
    <loginhibit onsuccess="true" />
  </stage>
  <stage stageid="62f141fd-127b-4e99-8d27-01eaf39da72e" name="IN" type="Block">
    <subsheetid>8d4786ca-281a-4044-8e18-eb97d785b992</subsheetid>
    <loginhibit onsuccess="true" />
  </stage>
  <stage stageid="beeb1d7f-47e9-4933-83fb-f770b335f7e6" name="INTERNAL" type="Block">
    <subsheetid>fc4e6ade-7a8d-4587-bfe3-21dbe933d8eb</subsheetid>
    <loginhibit onsuccess="true" />
  </stage>
  <stage stageid="901d6f98-d7c7-47d3-ba29-2ff2df2480fd" name="OUT" type="Block">
    <subsheetid>fc4e6ade-7a8d-4587-bfe3-21dbe933d8eb</subsheetid>
    <loginhibit onsuccess="true" />
  </stage>
  <stage stageid="428537b3-3aba-4b2b-aa25-c3ce5a0c8a6b" name="IN" type="Block">
    <subsheetid>fc4e6ade-7a8d-4587-bfe3-21dbe933d8eb</subsheetid>
    <loginhibit onsuccess="true" />
  </stage>
  <stage stageid="7f6a94a1-19b8-4ce0-b4db-16989dcd817f" name="Récupérer Mail Non Lu" type="Action">
    <subsheetid>fc4e6ade-7a8d-4587-bfe3-21dbe933d8eb</subsheetid>
    <onsuccess>e8c8c077-762d-41f3-b851-d49a0d41cdd7</onsuccess>
    <resource object="Blue Prism MAPIEx" action="Get Mail" />
  </stage>
  <stage stageid="e8c8c077-762d-41f3-b851-d49a0d41cdd7" name="Success ?" type="Decision">
    <subsheetid>fc4e6ade-7a8d-4587-bfe3-21dbe933d8eb</subsheetid>
    <decision expression="[Success]" />
    <ontrue>0f8992bb-a804-423f-b271-2809b0d7be9b</ontrue>
    <onfalse>a551fd19-b67d-40e1-9720-9158fbd7da59</onfalse>
  </stage>
  <stage stageid="0f8992bb-a804-423f-b271-2809b0d7be9b" name="Recup Info PJ" type="SubSheet">
    <subsheetid>fc4e6ade-7a8d-4587-bfe3-21dbe933d8eb</subsheetid>
    <onsuccess>0bc2c6b8-6571-42db-8d63-9334dc461fd7</onsuccess>
    <processid>614059a1-8f73-40c0-9dab-a3e78c79ecad</processid>
  </stage>
  <stage stageid="d0651705-f535-4c96-ac3f-c59a09560dd1" name="INTERNAL" type="Block">
    <subsheetid>61a0ac13-8edb-407b-9f5c-21990581f384</subsheetid>
    <loginhibit onsuccess="true" />
  </stage>
  <stage stageid="93cb1800-acb6-44f0-a58c-062d533f5d61" name="OUT" type="Block">
    <subsheetid>61a0ac13-8edb-407b-9f5c-21990581f384</subsheetid>
    <loginhibit onsuccess="true" />
  </stage>
  <stage stageid="144cc1e7-4066-4640-acfa-58689d2d7bd4" name="IN" type="Block">
    <subsheetid>61a0ac13-8edb-407b-9f5c-21990581f384</subsheetid>
    <loginhibit onsuccess="true" />
  </stage>
  <stage stageid="bf9cfc59-b7c3-4fc1-b587-0b7fe683f019" name="INTERNAL" type="Block">
    <subsheetid>614059a1-8f73-40c0-9dab-a3e78c79ecad</subsheetid>
    <loginhibit onsuccess="true" />
  </stage>
  <stage stageid="21d14d8b-8b24-42b3-a16b-05785604e704" name="OUT" type="Block">
    <subsheetid>614059a1-8f73-40c0-9dab-a3e78c79ecad</subsheetid>
    <loginhibit onsuccess="true" />
  </stage>
  <stage stageid="95f295b9-6c89-4823-8a7a-5de277a507cc" name="IN" type="Block">
    <subsheetid>614059a1-8f73-40c0-9dab-a3e78c79ecad</subsheetid>
    <loginhibit onsuccess="true" />
  </stage>
  <stage stageid="0bc2c6b8-6571-42db-8d63-9334dc461fd7" name="Ajouter liste à la Queue" type="Action">
    <subsheetid>fc4e6ade-7a8d-4587-bfe3-21dbe933d8eb</subsheetid>
    <loginhibit onsuccess="true" />
    <onsuccess>66df9185-c3a7-411a-9a2e-de6631ae8109</onsuccess>
    <resource object="Blueprism.Automate.clsWorkQueuesActions" action="Add To Queue" />
  </stage>
  <stage stageid="3be32c2e-6070-493e-8eb2-de6c95f89aa7" name="Liste Fournisseur" type="Collection">
    <subsheetid>fc4e6ade-7a8d-4587-bfe3-21dbe933d8eb</subsheetid>
    <datatype>collection</datatype>
    <private />
    <alwaysinit />
  </stage>
  <stage stageid="66df9185-c3a7-411a-9a2e-de6631ae8109" name="Queue Loaded" type="Calculation">
    <subsheetid>fc4e6ade-7a8d-4587-bfe3-21dbe933d8eb</subsheetid>
    <loginhibit onsuccess="true" />
    <onsuccess>78104125-e39e-49aa-b0b3-d0d12e743963</onsuccess>
    <calculation expression="True" stage="Queue Loaded" />
  </stage>
  <stage stageid="a551fd19-b67d-40e1-9720-9158fbd7da59" name="End5" type="End">
    <subsheetid>fc4e6ade-7a8d-4587-bfe3-21dbe933d8eb</subsheetid>
    <loginhibit onsuccess="true" />
  </stage>
  <stage stageid="78104125-e39e-49aa-b0b3-d0d12e743963" name="End5" type="End">
    <subsheetid>fc4e6ade-7a8d-4587-bfe3-21dbe933d8eb</subsheetid>
    <loginhibit onsuccess="true" />
  </stage>
  <stage stageid="afe9af7d-ed82-4db0-a54e-d41b48ee2f79" name="Queue Loaded" type="Data">
    <subsheetid>fc4e6ade-7a8d-4587-bfe3-21dbe933d8eb</subsheetid>
    <datatype>flag</datatype>
    <initialvalue>False</initialvalue>
    <private />
    <alwaysinit />
  </stage>
  <stage stageid="2a9f9603-e79a-40be-8c9b-8721309956a7" name="Sender Email Address" type="Data">
    <subsheetid>fc4e6ade-7a8d-4587-bfe3-21dbe933d8eb</subsheetid>
    <datatype>text</datatype>
    <initialvalue />
    <private />
    <alwaysinit />
  </stage>
  <stage stageid="547763e8-2824-4133-87ae-fe94e1b39a72" name="Subject" type="Data">
    <subsheetid>fc4e6ade-7a8d-4587-bfe3-21dbe933d8eb</subsheetid>
    <datatype>text</datatype>
    <initialvalue />
    <private />
    <alwaysinit />
  </stage>
  <stage stageid="98988ac3-f09e-4e29-a3f8-3b1da2092507" name="Attachment Count" type="Data">
    <subsheetid>fc4e6ade-7a8d-4587-bfe3-21dbe933d8eb</subsheetid>
    <datatype>number</datatype>
    <initialvalue />
    <private />
    <alwaysinit />
  </stage>
  <stage stageid="b002fa86-5bb8-4d10-8685-76c524cfe21f" name="Attachment Names" type="Data">
    <subsheetid>fc4e6ade-7a8d-4587-bfe3-21dbe933d8eb</subsheetid>
    <datatype>text</datatype>
    <initialvalue />
    <private />
    <alwaysinit />
  </stage>
  <stage stageid="5f25ecba-11d1-4064-a589-ecbb83b66e0e" name="Success" type="Data">
    <subsheetid>fc4e6ade-7a8d-4587-bfe3-21dbe933d8eb</subsheetid>
    <datatype>flag</datatype>
    <initialvalue />
    <private />
    <alwaysinit />
  </stage>
  <stage stageid="b85c1848-7d3c-4519-b168-d5fbc3d35646" name="Error Message" type="Data">
    <subsheetid>fc4e6ade-7a8d-4587-bfe3-21dbe933d8eb</subsheetid>
    <datatype>text</datatype>
    <initialvalue />
    <private />
    <alwaysinit />
  </stage>
  <stage stageid="4ccdb20c-dea8-47af-aaec-c2f6c9fae406" name="Credential valid ?" type="Decision">
    <subsheetid>959ff625-d504-46a0-8f6f-2930188215fe</subsheetid>
    <loginhibit onsuccess="true" />
    <decision expression="[Status]=&quot;Valid&quot;" />
    <ontrue>58c001bf-4df4-4295-84fe-3fa2bf5aa08d</ontrue>
    <onfalse>6739a184-46e2-4965-858c-602c3dd25654</onfalse>
  </stage>
  <stage stageid="02a104e4-4967-419b-9cfe-ced64c2e18ff" name="Get RMPM Credentials" type="Action">
    <subsheetid>959ff625-d504-46a0-8f6f-2930188215fe</subsheetid>
    <loginhibit onsuccess="true" />
    <onsuccess>4ccdb20c-dea8-47af-aaec-c2f6c9fae406</onsuccess>
    <resource object="Blueprism.Automate.clsCredentialsActions" action="Get" />
  </stage>
  <stage stageid="a5cadcb9-1121-4b90-8304-7d6ab7a16043" name="Queue Loaded" type="Data">
    <datatype>flag</datatype>
    <initialvalue />
    <private />
    <alwaysinit />
  </stage>
  <stage stageid="c1485c80-a7a5-4437-9f11-b5fca0989c88" name="Work" type="Block">
  </stage>
  <stage stageid="025b1dab-01fb-44f6-a9c7-aa4ea3e81ed1" name="Mark Item As Completed" type="SubSheet">
    <loginhibit onsuccess="true" />
    <onsuccess>f97bddaa-2b73-455b-ae83-3fbeab8723bf</onsuccess>
    <processid>0fd80767-2fc1-41e9-ae80-73ac1738dda1</processid>
  </stage>
  <stage stageid="2501e977-50cf-43cb-8a2a-c899097ad8ce" name="Recover" type="Recover">
    <loginhibit onsuccess="true" />
    <onsuccess>94f176aa-d377-4eed-93aa-4fa491142748</onsuccess>
  </stage>
  <stage stageid="94f176aa-d377-4eed-93aa-4fa491142748" name="Exception Data" type="MultipleCalculation">
    <loginhibit onsuccess="true" />
    <onsuccess>42d1c602-9fdf-4354-ae14-75eab94e9509</onsuccess>
    <steps>
      <calculation expression="ExceptionType()" stage="Exception Info.Type" />
      <calculation expression="ExceptionDetail()" stage="Exception Info.Detail" />
      <calculation expression="ExceptionStage()" stage="Exception Info.Stage" />
    </steps>
  </stage>
  <stage stageid="42d1c602-9fdf-4354-ae14-75eab94e9509" name="Resume" type="Resume">
    <loginhibit onsuccess="true" />
    <onsuccess>be668461-6715-4ae3-a58e-e61a2d40035d</onsuccess>
  </stage>
  <stage stageid="f34e683b-e9d3-4e6b-b982-c990d97e5583" name="Recover4" type="Recover">
    <loginhibit onsuccess="true" />
    <onsuccess>0e7e1319-6c48-4d87-aed5-b198415c827b</onsuccess>
  </stage>
  <stage stageid="0e7e1319-6c48-4d87-aed5-b198415c827b" name="Resume2" type="Resume">
    <loginhibit onsuccess="true" />
    <onsuccess>da796845-26df-47d9-a1c2-7843205a8c9f</onsuccess>
  </stage>
  <stage stageid="f8587b69-c149-4ad5-a9d5-675f53645402" name="Notify Exception" type="Block">
    <loginhibit onsuccess="true" />
  </stage>
  <stage stageid="da796845-26df-47d9-a1c2-7843205a8c9f" name="Mark Item As Exception" type="SubSheet">
    <loginhibit onsuccess="true" />
    <onsuccess>cc035011-f78e-40ec-8175-997546e373c6</onsuccess>
    <processid>bb122fc4-3e3e-4e96-acb7-62104bb07f35</processid>
  </stage>
  <stage stageid="cc035011-f78e-40ec-8175-997546e373c6" name="anchor14" type="Anchor">
    <loginhibit onsuccess="true" />
    <onsuccess>f97bddaa-2b73-455b-ae83-3fbeab8723bf</onsuccess>
  </stage>
  <stage stageid="f97bddaa-2b73-455b-ae83-3fbeab8723bf" name="Anchor1" type="Anchor">
    <onsuccess>7ce59389-58f1-4f79-a9b3-9aef63fb39ba</onsuccess>
  </stage>
  <stage stageid="be668461-6715-4ae3-a58e-e61a2d40035d" name="Notify_Exception" type="SubSheet">
    <loginhibit onsuccess="true" />
    <onsuccess>da796845-26df-47d9-a1c2-7843205a8c9f</onsuccess>
    <processid>0419341b-8a5d-45b3-9ca3-71b8d47ffff0</processid>
  </stage>
  <stage stageid="53e1eb5a-4523-4ddb-a44f-38d94d58ec44" name="Recover4" type="Recover">
    <loginhibit onsuccess="true" />
    <onsuccess>d838cf81-ba61-4402-8777-cb974047c170</onsuccess>
  </stage>
  <stage stageid="45233aea-b695-4c24-bd81-017ec2eb1c7e" name="Termination" type="SubSheet">
    <loginhibit onsuccess="true" />
    <onsuccess>7b44448d-884f-4f34-8eac-c1a1ff0414f9</onsuccess>
    <processid>4bf72baa-85cd-49b1-aee7-2f7173f35a18</processid>
  </stage>
  <stage stageid="e227be1b-b37c-47ec-94b2-339ff96f96a7" name="Resume1" type="Resume">
    <onsuccess>45233aea-b695-4c24-bd81-017ec2eb1c7e</onsuccess>
  </stage>
  <stage stageid="7b44448d-884f-4f34-8eac-c1a1ff0414f9" name="End" type="End">
  </stage>
  <stage stageid="aa04fca1-bf28-49d7-8b6a-009aac7b8942" name="Termination" type="Block">
    <loginhibit onsuccess="true" />
  </stage>
  <stage stageid="038111f2-ca08-44f2-8225-8a4563900b59" name="Recover2" type="Recover">
    <onsuccess>84af0575-4936-4160-9ca8-744604c367ee</onsuccess>
  </stage>
  <stage stageid="84af0575-4936-4160-9ca8-744604c367ee" name="Exception6" type="Exception">
    <exception type="" detail="" usecurrent="yes" />
  </stage>
  <stage stageid="f9264c47-2edb-426b-91ff-0d3264ce364c" name="01 - Recherche Fournisseur" type="SubSheet">
    <onsuccess>d7ea1541-21a8-4e3d-a984-225ab7b97f2e</onsuccess>
    <processid>61a0ac13-8edb-407b-9f5c-21990581f384</processid>
  </stage>
  <stage stageid="d7ea1541-21a8-4e3d-a984-225ab7b97f2e" name="02 - Finalisation" type="SubSheet">
    <onsuccess>025b1dab-01fb-44f6-a9c7-aa4ea3e81ed1</onsuccess>
    <processid>b9d01bbd-d50f-408d-a57d-f5def6ddbaf6</processid>
  </stage>
  <stage stageid="87dc7b90-1ff8-4390-867a-6b2cc02db345" name="Password" type="Data">
    <subsheetid>959ff625-d504-46a0-8f6f-2930188215fe</subsheetid>
    <datatype>password</datatype>
    <initialvalueenc>
    </initialvalueenc>
    <private />
    <alwaysinit />
  </stage>
  <stage stageid="1c713b66-7d7c-4c19-a994-f0102b1b7a23" name="Username" type="Data">
    <subsheetid>959ff625-d504-46a0-8f6f-2930188215fe</subsheetid>
    <datatype>text</datatype>
    <initialvalue />
    <private />
    <alwaysinit />
  </stage>
  <stage stageid="33a1ba1e-9f1d-49fe-8671-d4238106ee93" name="Expiry Date" type="Data">
    <subsheetid>959ff625-d504-46a0-8f6f-2930188215fe</subsheetid>
    <datatype>date</datatype>
    <initialvalue />
    <private />
    <alwaysinit />
  </stage>
  <stage stageid="6290da4b-6aa5-4126-8e2b-48981bea4876" name="Status" type="Data">
    <subsheetid>959ff625-d504-46a0-8f6f-2930188215fe</subsheetid>
    <datatype>text</datatype>
    <initialvalue />
    <private />
    <alwaysinit />
  </stage>
  <stage stageid="844a7ac3-82c7-40c4-8247-a7b932e8ff41" name="Mark Item As Completed" type="SubSheetInfo">
    <subsheetid>0fd80767-2fc1-41e9-ae80-73ac1738dda1</subsheetid>
    <loginhibit onsuccess="true" />
  </stage>
  <stage stageid="48ff8015-f112-4498-b63b-cc5fb85fb88a" name="Start" type="Start">
    <subsheetid>0fd80767-2fc1-41e9-ae80-73ac1738dda1</subsheetid>
    <loginhibit onsuccess="true" />
    <onsuccess>5904d1b2-6ec2-429e-9151-e230c7928fb5</onsuccess>
  </stage>
  <stage stageid="d937c11d-a3e3-43cd-9b63-5396f87bf6d6" name="Mark Completed" type="Action">
    <subsheetid>0fd80767-2fc1-41e9-ae80-73ac1738dda1</subsheetid>
    <loginhibit onsuccess="true" />
    <onsuccess>c2e4eb92-79e8-470e-a0b8-cfed73ff923b</onsuccess>
    <resource object="Blueprism.Automate.clsWorkQueuesActions" action="Mark Completed" />
  </stage>
  <stage stageid="5904d1b2-6ec2-429e-9151-e230c7928fb5" name="Set Status" type="Action">
    <subsheetid>0fd80767-2fc1-41e9-ae80-73ac1738dda1</subsheetid>
    <loginhibit onsuccess="true" />
    <onsuccess>d937c11d-a3e3-43cd-9b63-5396f87bf6d6</onsuccess>
    <resource object="Blueprism.Automate.clsWorkQueuesActions" action="Update Status" />
  </stage>
  <stage stageid="c2e4eb92-79e8-470e-a0b8-cfed73ff923b" name="Reset Consecutive Exception Indicators" type="MultipleCalculation">
    <subsheetid>0fd80767-2fc1-41e9-ae80-73ac1738dda1</subsheetid>
    <loginhibit onsuccess="true" />
    <onsuccess>bcd93ebe-195f-4539-93c2-b6cba13a83c3</onsuccess>
    <steps>
      <calculation expression="&quot;&quot;" stage="Previous Exception Detail" />
      <calculation expression="0" stage="Consecutive Exception Count" />
    </steps>
  </stage>
  <stage stageid="bcd93ebe-195f-4539-93c2-b6cba13a83c3" name="End3" type="End">
    <subsheetid>0fd80767-2fc1-41e9-ae80-73ac1738dda1</subsheetid>
    <loginhibit onsuccess="true" />
  </stage>
  <stage stageid="10b43741-cefc-4858-b582-c3480b43ffd7" name="INTERNAL" type="Block">
    <subsheetid>0fd80767-2fc1-41e9-ae80-73ac1738dda1</subsheetid>
    <loginhibit onsuccess="true" />
  </stage>
  <stage stageid="8a0c182d-f2ed-4ce2-b890-af7e80ec61cd" name="OUT" type="Block">
    <subsheetid>0fd80767-2fc1-41e9-ae80-73ac1738dda1</subsheetid>
    <loginhibit onsuccess="true" />
  </stage>
  <stage stageid="ba3f57e7-0128-44cf-b5b3-bb03020f7769" name="IN" type="Block">
    <subsheetid>0fd80767-2fc1-41e9-ae80-73ac1738dda1</subsheetid>
    <loginhibit onsuccess="true" />
  </stage>
  <stage stageid="355f4b16-2e26-4dbd-8bb5-675f877d2e58" name="Item ID" type="Data">
    <subsheetid>0fd80767-2fc1-41e9-ae80-73ac1738dda1</subsheetid>
    <loginhibit onsuccess="true" />
    <datatype>text</datatype>
    <initialvalue />
    <private />
    <alwaysinit />
  </stage>
  <stage stageid="38586c23-8b58-4e00-a18e-1c797c88f273" name="Mark Item As Exception" type="SubSheetInfo">