<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE process [
        <!ELEMENT process (stage|subsheet)*>
        <!ATTLIST process
                name CDATA #REQUIRED
                type CDATA #REQUIRED>
        <!ELEMENT stage (displayx|displayy|displaywidth|displayheight|subsheetid)*>
        <!ATTLIST stage
                name CDATA #REQUIRED
                stageid CDATA #REQUIRED
                type CDATA #REQUIRED>
        <!ELEMENT displayx (#PCDATA)>
        <!ELEMENT displayy (#PCDATA)>
        <!ELEMENT displaywidth (#PCDATA)>
        <!ELEMENT displayheight (#PCDATA)>
        <!ELEMENT subsheet (name)*>
        <!ATTLIST subsheet
                subsheetid CDATA #REQUIRED>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT subsheetid (#PCDATA)>
        ]>
<process name="WebPOC" type="object">
    <stage name="Stage1" stageid="4cfaf684-64d7-42a8-b98f-da722634c36a" type="ProcessInfo">
        <displayx>-195</displayx>
        <displayy>-105</displayy>
        <displaywidth>150</displaywidth>
        <displayheight>90</displayheight>
    </stage>
    <stage name="Start" stageid="0e62773b-82c1-49a8-b30f-c0dd4615cb0d" type="Start">
        <displayx>15</displayx>
        <displayy>-105</displayy>
        <displaywidth>60</displaywidth>
        <displayheight>30</displayheight>
    </stage>
    <stage name="End" stageid="bcb2a329-8e40-4510-862d-9335dbb1b002" type="End">
        <displayx>15</displayx>
        <displayy>90</displayy>
        <displaywidth>60</displaywidth>
        <displayheight>30</displayheight>
    </stage>
    <subsheet subsheetid="51158098-5956-3ccb-8e22-19088c02d252">
        <name>Lancer</name>
    </subsheet>
    <stage name="Lancer" stageid="13420c3c-f07a-4e2e-989f-b0dfb8eb2c7c" type="SubSheetInfo">
        <subsheetid>51158098-5956-3ccb-8e22-19088c02d252</subsheetid>
        <displayx>-195</displayx>
        <displayy>-105</displayy>
        <displaywidth>150</displaywidth>
        <displayheight>90</displayheight>
    </stage>
    <stage name="Start" stageid="71a93153-907a-4ca8-8214-838e7fe1f456" type="Start">
        <subsheetid>51158098-5956-3ccb-8e22-19088c02d252</subsheetid>
        <displayx>15</displayx>
        <displayy>-105</displayy>
        <displaywidth>60</displaywidth>
        <displayheight>30</displayheight>
    </stage>
    <stage name="End" stageid="2d3995ea-2979-4e34-94d5-e99dceb9acb1" type="End">
        <subsheetid>51158098-5956-3ccb-8e22-19088c02d252</subsheetid>
        <displayx>15</displayx>
        <displayy>90</displayy>
        <displaywidth>60</displaywidth>
        <displayheight>30</displayheight>
    </stage>
    <subsheet subsheetid="d46bc993-538f-38b6-8c6b-171673903af2">
        <name>Connexion</name>
    </subsheet>
    <stage name="Connexion" stageid="589d5f0b-8c70-45cd-8c15-6f3813c4933c" type="SubSheetInfo">
        <subsheetid>d46bc993-538f-38b6-8c6b-171673903af2</subsheetid>
        <displayx>-195</displayx>
        <displayy>-105</displayy>
        <displaywidth>150</displaywidth>
        <displayheight>90</displayheight>
    </stage>
    <stage name="Start" stageid="edbe3775-7807-4606-a02a-6aa2b0fd260c" type="Start">
        <subsheetid>d46bc993-538f-38b6-8c6b-171673903af2</subsheetid>
        <displayx>15</displayx>
        <displayy>-105</displayy>
        <displaywidth>60</displaywidth>
        <displayheight>30</displayheight>
    </stage>
    <stage name="End" stageid="4fb42b43-989d-4a89-983d-f1955e95ed07" type="End">
        <subsheetid>d46bc993-538f-38b6-8c6b-171673903af2</subsheetid>
        <displayx>15</displayx>
        <displayy>90</displayy>
        <displaywidth>60</displaywidth>
        <displayheight>30</displayheight>
    </stage>
    <subsheet subsheetid="e3e4a631-d0a1-3479-a496-6c1800d6e975">
        <name>Fermeture</name>
    </subsheet>
    <stage name="Fermeture" stageid="74d2b6cc-59e3-4236-ae8e-1bc8cd803475" type="SubSheetInfo">
        <subsheetid>e3e4a631-d0a1-3479-a496-6c1800d6e975</subsheetid>
        <displayx>-195</displayx>
        <displayy>-105</displayy>
        <displaywidth>150</displaywidth>
        <displayheight>90</displayheight>
    </stage>
    <stage name="Start" stageid="e799d6f8-4072-4cf6-8e3a-dc8e1313d6b5" type="Start">
        <subsheetid>e3e4a631-d0a1-3479-a496-6c1800d6e975</subsheetid>
        <displayx>15</displayx>
        <displayy>-105</displayy>
        <displaywidth>60</displaywidth>
        <displayheight>30</displayheight>
    </stage>
    <stage name="End" stageid="01430c26-906a-4238-b786-af27c0c0de67" type="End">
        <subsheetid>e3e4a631-d0a1-3479-a496-6c1800d6e975</subsheetid>
        <displayx>15</displayx>
        <displayy>90</displayy>
        <displaywidth>60</displaywidth>
        <displayheight>30</displayheight>
    </stage>
    <subsheet subsheetid="d5277799-a044-3ad9-9204-d8af35bf388a">
        <name>Accès_Recherche_Fournisseur</name>
    </subsheet>
    <stage name="Accès_Recherche_Fournisseur" stageid="caf28b3a-18b1-4a5b-b62e-ca7c90df18bc" type="SubSheetInfo">
        <subsheetid>d5277799-a044-3ad9-9204-d8af35bf388a</subsheetid>
        <displayx>-195</displayx>
        <displayy>-105</displayy>
        <displaywidth>150</displaywidth>
        <displayheight>90</displayheight>
    </stage>
    <stage name="Start" stageid="770a877b-ef32-4fe6-997a-c280226d9820" type="Start">
        <subsheetid>d5277799-a044-3ad9-9204-d8af35bf388a</subsheetid>
        <displayx>15</displayx>
        <displayy>-105</displayy>
        <displaywidth>60</displaywidth>
        <displayheight>30</displayheight>
    </stage>
    <stage name="End" stageid="ba66c79a-f015-4129-bded-6d060f7f3a5f" type="End">
        <subsheetid>d5277799-a044-3ad9-9204-d8af35bf388a</subsheetid>
        <displayx>15</displayx>
        <displayy>90</displayy>
        <displaywidth>60</displaywidth>
        <displayheight>30</displayheight>
    </stage>
    <subsheet subsheetid="bb7c6f86-d622-35e2-b04e-35e411e5ed9f">
        <name>Saisie_Recherche_Fournisseur</name>
    </subsheet>
    <stage name="Saisie_Recherche_Fournisseur" stageid="c4b004d4-83a3-4688-bd2f-880c29b2d225" type="SubSheetInfo">
        <subsheetid>bb7c6f86-d622-35e2-b04e-35e411e5ed9f</subsheetid>
        <displayx>-195</displayx>
        <displayy>-105</displayy>
        <displaywidth>150</displaywidth>
        <displayheight>90</displayheight>
    </stage>
    <stage name="Start" stageid="d8f615c9-9cd7-41a5-b45e-8aa57216df0e" type="Start">
        <subsheetid>bb7c6f86-d622-35e2-b04e-35e411e5ed9f</subsheetid>
        <displayx>15</displayx>
        <displayy>-105</displayy>
        <displaywidth>60</displaywidth>
        <displayheight>30</displayheight>
    </stage>
    <stage name="End" stageid="a79902ae-237e-463f-86c8-9d0b6dd50a1d" type="End">
        <subsheetid>bb7c6f86-d622-35e2-b04e-35e411e5ed9f</subsheetid>
        <displayx>15</displayx>
        <displayy>90</displayy>
        <displaywidth>60</displaywidth>
        <displayheight>30</displayheight>
    </stage>
    <subsheet subsheetid="73f35d8b-63d0-343c-8789-420df59d33f5">
        <name>Récupération_Info_Fournisseur</name>
    </subsheet>
    <stage name="Récupération_Info_Fournisseur" stageid="6d2db7f3-8404-4d1a-a196-50ea224e4c4c" type="SubSheetInfo">
        <subsheetid>73f35d8b-63d0-343c-8789-420df59d33f5</subsheetid>
        <displayx>-195</displayx>
        <displayy>-105</displayy>
        <displaywidth>150</displaywidth>
        <displayheight>90</displayheight>
    </stage>
    <stage name="Start" stageid="dd91e3e7-73aa-4d4d-be03-b32fa1736adc" type="Start">
        <subsheetid>73f35d8b-63d0-343c-8789-420df59d33f5</subsheetid>
        <displayx>15</displayx>
        <displayy>-105</displayy>
        <displaywidth>60</displaywidth>
        <displayheight>30</displayheight>
    </stage>
    <stage name="End" stageid="dcf5ee0e-3321-49a7-8be6-b82de60766d9" type="End">
        <subsheetid>73f35d8b-63d0-343c-8789-420df59d33f5</subsheetid>
        <displayx>15</displayx>
        <displayy>90</displayy>
        <displaywidth>60</displaywidth>
        <displayheight>30</displayheight>
    </stage>
</process>
